feat(note): Move cache outside secrets, per-host
This answers a substantial problem with the notes: they were taking too
much space! And part of the issue was storing PDFs inside the secrets.
Now, cache is stored in a separate directory, which is outside secrets.
This means caching happens at view time, not at edit time (which is
another hidden enhancement, because the simpler edits are, the lower the
possibility of errors and data loss).

I dropped the strsub 3rd argument functionality, because I genuinely
don't think it has any use anymore. I don't remember why it was
introduced.

diff --git a/modules/home-manager/note-utils/localbin/note b/modules/home-manager/note-utils/localbin/note
--- a/modules/home-manager/note-utils/localbin/note
+++ b/modules/home-manager/note-utils/localbin/note
@@ -20,6 +20,7 @@ set -e
 
 # CONFIG
 NOTES="${XDG_DATA_HOME:-~/.local/share}/notes"
+NOTES_CACHE="$NOTES/.cache"
 SECRETS="$NOTES/secrets"
 PDF_READER="${PDF_READER:-zathura}"
 BROWSER="${BROWSER:-firefox}"
@@ -77,21 +78,15 @@ String Substitutions:
 "
 }
 
-# strsub <source> <file> <use_current_time?>
+# strsub <source> <file>
 # Does in-place string substitution, as described in --help.
 # source is the file that will be stat'ted for information
 # SOURCE MUST BE A NOTES GIT REPO FILE!!!
 # file is the file that will be modified with substitutions
-# If use_current_time is passed, NOTE_MTIME will be substituted
-# for the current time, instead of fetching the latest git commit.
 strsub () {
     # Update modified time according to git data
     fpath="$(realpath --relative-to "$SECRETS" -- "$1")"
-    if [ -z "$3" ]; then
-        epoch="$(git -C "$SECRETS" log -1 --format='%at' -- "$fpath")"
-    else
-        epoch="$(date +%s)"
-    fi
+    epoch="$(git -C "$SECRETS" log -1 --format='%at' -- "$fpath")"
     touch -mct "$(date -d "@$epoch" '+%Y%m%d%H%M.%S')" -- "$1"
 
     mtime="$(date -d "@$epoch" '+%a %Y-%m-%d %H:%M %Z')"
@@ -123,40 +118,9 @@ edit () {
     if ! secrets modified "$NOTES" >/dev/null; then
         echo 'No changes were made, skipping.'
     else
-        # Custom postprocessing based on file type.
-        # Disable exiting on error here, to prioritize saving the changes.
-        set +e
-        case "$ext" in
-            tex)
-                # Cache the PDF for quick access
-                notemain2="$(mktemp -p "$dir" tmp.XXXXX)"
-                cp -- "$notemain" "$notemain2"
-                strsub "$notemain" "$notemain2" 1
-                lxmake "$notemain2" "$dir/.cache.pdf"
-                rm -f -- "$notemain2"
-                ;;
-            typ)
-                # Cache the PDF for quick access
-                notemain2="$(mktemp -p "$dir" tmp.XXXXX)"
-                cp -- "$notemain" "$notemain2"
-                strsub "$notemain" "$notemain2" 1
-                typst compile -- "$notemain2" "$dir/.cache.pdf"
-                rm -f -- "$notemain2"
-                ;;
-            ly)
-                # Cache the PDF for quick access
-                notemain2="$(mktemp -p "$dir" tmp.XXXXX)"
-                cp -- "$notemain" "$notemain2"
-                strsub "$notemain" "$notemain2" 1
-                lilypond -s -o "$dir/.cache" "$notemain2"
-                rm -f -- "$notemain2"
-                ;;
-        esac
-
         git -C "$SECRETS" add -- "$note"
         git -C "$SECRETS" commit -m "Edit $note" -- "$note"
         secrets save "$NOTES"
-        set -e
     fi
 }
 
@@ -167,6 +131,16 @@ view () {
     ext="${note##*.}"
     dir="$SECRETS/$note"
     notemain="$dir/$(basename -- "$note")"
+
+    # Delegate cached note types to view_cached()
+    case "$ext" in
+        tex|typ|ly)
+            view_cached "$@"
+            return $?
+            ;;
+        *) ;;
+    esac
+
     # TODO?: this is unnecessary for cached notes
     tmpd="$(mktemp --tmpdir -d note.XXXXX)"
     tmpdmain="$tmpd/$(basename -- "$note")"
@@ -190,40 +164,89 @@ view () {
             md2html --github -- "$tmpdmain" >>"$tmp"
             [ -s "$tmp" ] && $BROWSER file://"$tmp" && sleep 2  # Browsers tend to be non-blocking, so wait a bit before deleting
             ;;
-        tex)
-            cache="$dir/.cache.pdf"
-            # Ensure PDF cache exists
-            [ ! -f "$cache" ] && {
-                lxmake "$tmpdmain" "$cache"
-                git -C "$SECRETS" add -- "$cache"
-                git -C "$SECRETS" commit -m "Cache $note" -- "$cache"
-            }
-            $PDF_READER - <"$cache"
-            ;;
-        typ)
-            cache="$dir/.cache.pdf"
-            # Ensure PDF cache exists
-            [ ! -f "$cache" ] && {
-                typst compile -- "$tmpdmain" "$cache"
-                git -C "$SECRETS" add -- "$cache"
-                git -C "$SECRETS" commit -m "Cache $note" -- "$cache"
-            }
-            $PDF_READER - <"$cache"
-            ;;
-        ly)
-            cache="$dir/.cache.pdf"
-            # Ensure PDF cache exists
-            [ ! -f "$cache" ] && {
-                lilypond -s -o "${cache%.pdf}" "$tmpdmain"
-                git -C "$SECRETS" add -- "$cache"
-                git -C "$SECRETS" commit -m "Cache $note" -- "$cache"
-            }
-            $PDF_READER - <"$cache"
-            ;;
         *)
             printf "note: unknown note format '%s'\n" "$ext" >&2
     esac
     rm -rf -- "$tmpd"
+}
+
+# view_cached <note>
+# note - path to the note subdirectory, relative to $NOTES
+# This function is same as view(), except it assumes the note uses caching and
+# will attempt to find the cached file, and will generate it if it does not
+# exist.
+view_cached () {
+    note="$1"
+    ext="${note##*.}"
+    dir="$SECRETS/$note"
+    notemain="$dir/$(basename -- "$note")"
+
+    cache_fpath=
+    case "$ext" in
+        tex|typ|ly) cache_fpath="$NOTES_CACHE/$(echo "$dir" | md5sum | cut -d' ' -f1).pdf" ;;
+        *)
+            echo "note: internal error! extension not recognized as cacheable: $ext" >&2
+            exit 3
+            ;;
+    esac
+
+    # Read mtime of the note. Will be useful later
+    src_fpath="$dir/$(basename -- "$note")"
+    [ ! -f "$src_fpath" ] && echo "note: $src_fpath not found!" >&2 && exit 3
+    src_epoch="$(git -C "$SECRETS" log -1 --format='%at' -- "$src_fpath")"
+
+    cache_exists_and_matches_src=
+    if [ -n "$cache_fpath" ] && [ -f "$cache_fpath" ]; then
+        # Compare mtime of cache and source
+        cache_epoch="$(stat -c %Y -- "$cache_fpath")"
+        # We want exact equality here, because the cache cannot be outdated,
+        # but also we don't want it to "lie" to us if for some reason source
+        # regressed. The cache must reflect the exact version of the source.
+        [ "$cache_epoch" -eq "$src_epoch" ] && cache_exists_and_matches_src=1
+    fi
+
+    if [ -z "$cache_exists_and_matches_src" ]; then
+        # Create/update the cache
+        mkdir -p -- "$NOTES_CACHE"
+        case "$ext" in
+            tex)
+                notemain2="$(mktemp -p "$dir" tmp.XXXXX)"
+                cp -- "$notemain" "$notemain2"
+                strsub "$notemain" "$notemain2"
+                lxmake "$notemain2" - | secrets oe "$NOTES" - "$cache_fpath"
+                rm -f -- "$notemain2"
+                ;;
+            typ)
+                notemain2="$(mktemp -p "$dir" tmp.XXXXX)"
+                cp -- "$notemain" "$notemain2"
+                strsub "$notemain" "$notemain2"
+                typst compile -- "$notemain2" - | secrets oe "$NOTES" - "$cache_fpath"
+                rm -f -- "$notemain2"
+                ;;
+            ly)
+                notemain2="$(mktemp -p "$dir" tmp.XXXXX)"
+                tmppdf="$(mktemp --tmpdir note.XXXXX)"
+                cp -- "$notemain" "$notemain2"
+                strsub "$notemain" "$notemain2"
+                lilypond -s -o "$tmppdf" "$notemain2"  # lilypond doesn't support stdout export
+                secrets oe "$NOTES" "$tmppdf" "$cache_fpath"
+                rm -f -- "$notemain2" "$tmppdf"
+                ;;
+        esac
+        # Ensure the cache has the exact same mtime as the source from which it was generated.
+        touch -mct "$(date -d "@$src_epoch" '+%Y%m%d%H%M.%S')" -- "$cache_fpath"
+    fi
+
+    # View the cache
+    case "$cache_fpath" in
+        *.pdf)
+            secrets od "$NOTES" "$cache_fpath" - | $PDF_READER -
+            ;;
+        *)
+            echo "note: don't know how to view cache '$cache_fpath'" >&2
+            exit 3
+            ;;
+    esac
 }
 
 # create <note>
