fix(note): Disable set -e between editing and saving a note
I just lost some edits, presumably because some command failed between
me having finished the edit and the `secrets save` command running.
Never again, please.

diff --git a/modules/home-manager/note-utils/localbin/note b/modules/home-manager/note-utils/localbin/note
--- a/modules/home-manager/note-utils/localbin/note
+++ b/modules/home-manager/note-utils/localbin/note
@@ -124,6 +124,8 @@ edit () {
         echo 'No changes were made, skipping.'
     else
         # Custom postprocessing based on file type.
+        # Disable exiting on error here, to prioritize saving the changes.
+        set +e
         case "$ext" in
             tex)
                 # Cache the PDF for quick access
@@ -154,6 +156,7 @@ edit () {
         git -C "$SECRETS" add -- "$note"
         git -C "$SECRETS" commit -m "Edit $note" -- "$note"
         secrets save "$NOTES"
+        set -e
     fi
 }
 
