feat(secrets): Add modified action
This simplifies the logic in note and le scripts, and removes the need
for those scripts to have the dir_cksum function. Neat.

I had to work around one legitimate dir_cksum use case inside note -
that is when a new note gets created. But for that we can just use
`test -s`.

diff --git a/modules/home-manager/scripts/localbin/secrets b/modules/home-manager/scripts/localbin/secrets
--- a/modules/home-manager/scripts/localbin/secrets
+++ b/modules/home-manager/scripts/localbin/secrets
@@ -8,6 +8,7 @@ help () {
     echo 'Actions:'
     echo "  d|decrypt   Decrypt secrets.gpg into a tmpdir and symlink as secrets."
     echo "  s|save      Overwrite secrets.gpg to reflect the decrypted secrets."
+    echo "  m|modified  Checks whether the decrypted secrets have been modified."
     echo "  c|clean     Same as save, but also destroy the tmpdir and symlink."
 }
 
@@ -106,10 +107,33 @@ save () {
     fi
 }
 
+modified () {
+    # Error handling
+    if [ ! -L "$SECRETS" ]; then
+        echo 'secrets: the secrets are locked' >&2
+        exit 1
+    fi
+    secrets_dir="$(readlink -- "$SECRETS")"
+    if [ ! -d "$secrets_dir" ]; then
+        printf 'secrets: error! the secrets symlink does not point to a directory\n' >&2
+        exit 2
+    fi
+
+    prev_cksum="$(cat -- "$CHECKSUM" 2>/dev/null || :)"
+    if [ "$(dir_cksum "$secrets_dir")" = "$prev_cksum" ]; then
+        echo 'The secrets have not been modified.'
+        exit 1
+    else
+        echo 'The secrets have been modified.'
+        exit
+    fi
+}
+
 case "$ACTION" in
     d|decrypt) decrypt ;;
     s|save) save ;;
     c|clean) clean ;;
+    m|modified) modified ;;
     *)
         echo 'secrets: invalid action' >&2
         help
